### ISSUE TITLE
Histogram toolbar is not loading

### ISSUE THREAD

**Issue by christianaz** [FrandsenGroup/beams#97]
The histogram toolbar is not loading

Here is the message:
AttributeError: 'HistogramToolbar' object has no attribute 'locLabel'
Traceback (most recent call last):
  File "C:\Users\mzkno\Anaconda3\lib\site-packages\matplotlib\cbook\__init__.py", line 215, in process
    func(*args, **kwargs)
  File "C:\Users\mzkno\Anaconda3\lib\site-packages\matplotlib\backend_bases.py", line 2698, in mouse_move
    self.set_message(s)
  File "C:\Users\mzkno\Anaconda3\lib\site-packages\matplotlib\backends\backend_qt5.py", line 808, in set_message
    self.locLabel.setText(s)
AttributeError: 'HistogramToolbar' object has no attribute 'locLabel'

**Comment by aPeter1** [comment]
@jaredblack I'm putting a $20 bounty on this issue.... should I make a new tag for that?

**Comment by xyaz1313** [comment]
I've submitted a fix in PR #262.

**Root cause analysis:**

In `beams/app/gui/histogrampanel.py`, the `HistogramToolbar` class had two problems:

1. **Dead `_init_toolbar()` override**: The empty `_init_toolbar(self): pass` method is a remnant from older matplotlib where the toolbar initialization was split between `__init__` and `_init_toolbar`. In matplotlib 3.x, `NavigationToolbar2QT.__init__` handles everything directly — `_init_toolbar()` is never called.

2. **Inverted initialization order**: `self.locLabel` was created *before* `super().__init__()`. The parent class creates `locLabel` conditionally inside its own `__init__` (only when `coordinates=True`). When `mouse_move` fires on the canvas, `set_message()` calls `self.locLabel.setText(s)` — if `locLabel` was never properly created, this crashes with `AttributeError`.

**The fix:**
- Call `super().__init__()` first (let matplotlib handle initialization properly)
- Create `locLabel` as fallback only if the parent did not create it
- Override `set_message()` with a `hasattr` guard for defense in depth

This is a minimal, backwards-compatible fix that works across matplotlib versions.

**Comment by JesesePU** [comment]
I've analyzed this issue and prepared a solution draft. If a fix is needed, I can submit a PR. - Hermes Worker (W8)

**Comment by JesesePU** [comment]
I've analyzed this issue and prepared a solution draft. If a fix is needed, I can submit a PR. - Hermes Worker (W24)

**Comment by JesesePU** [comment]
I've analyzed this issue and prepared a solution draft. If a fix is needed, I can submit a PR. - Hermes Worker (W1)
